package com.customertracker.CustomerTracker.Models;

import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * This class represents a Customer's account.
 */
@Entity
@Table(name = "accounts")
public class Account {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;

  @ManyToOne
  private Customer customer;

  private String address;

  private String city;

  private String state;

  private Integer zipCode;

  private Integer solarFarmId;

  private double capacityShare;

  private Date createdDate;

  /**
   * Constructor constructs an Account object with all null or negative values representing an
   * empty account.
   */
  public Account() {
    this.customer = new Customer();
    this.address = null;
    this.city = null;
    this.state = null;
    this.zipCode = null;
    this.solarFarmId = null;
    this.capacityShare = -.01;
    this.createdDate = null;
  }

  /**
   * Constructor constructs an Account object and initializes all class variables according to the
   * passed in parameters.
   *
   * @param customer a Customer object representing the customer who owns the constructed Account
   *                 object.
   * @param address a String representing the address of the associated Account object.
   * @param city a String representing the city of the associated Account object.
   * @param state a String representing the state of the associated Account object.
   * @param zipCode an Integer representing the zip code for the associated Account object.
   * @param solarFarmId an Integer representing the ID for the associated Solar Farm of the Account
   *                    object.
   * @param capacityShare a double representing the capacity return from the associated solar farm
   *                      for the Account object.
   * @param createdDate a SQL date object representing the date the Account was created.
   */
  public Account(Customer customer, String address, String city, String state, Integer zipCode,
                 Integer solarFarmId, double capacityShare, Date createdDate) {
    this.customer = customer;
    this.address = address;
    this.city = city;
    this.state = state;
    this.zipCode = zipCode;
    this.solarFarmId = solarFarmId;
    this.capacityShare = capacityShare;
    this.createdDate = createdDate;
  }

  /**
   * This method returns the Account object's ID.
   *
   * @return an Integer representing the Account's ID.
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method sets the Account object's ID. This method does not work as the ID is auto
   * generated by the MySQL server.
   *
   * @param id an Integer representing the Account's ID.
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method returns the Account object's associated Customer object.
   *
   * @return a Customer object that owns the Account.
   */
  public Customer getCustomer() {
    return customer;
  }

  /**
   * This method sets the Account object's customer variable according to the passed parameter.
   *
   * @param customer a Customer object that owns the Account.
   */
  public void setCustomer(Customer customer) {
    this.customer = customer;
  }

  /**
   * This method returns the Account object's address.
   *
   * @return a String that represents the address the account is located at.
   */
  public String getAddress() {
    return address;
  }

  /**
   * This method sets the Account object's address variable according to the passed parameter.
   *
   * @param address a String that represents the address the account is located at.
   */
  public void setAddress(String address) {
    this.address = address;
  }

  /**
   * This method returns the Account object's city.
   *
   * @return a String that represents the city the account is located at.
   */
  public String getCity() {
    return city;
  }

  /**
   * This method sets the Account object's city variable according to the passed parameter.
   *
   * @param city a String that represents the city that the Account is located in.
   */
  public void setCity(String city) {
    this.city = city;
  }

  /**
   * This method returns the Account object's State.
   *
   * @return a String that represents the State the account is located in.
   */
  public String getState() {
    return state;
  }

  /**
   * This method sets the Account object's state variable according to the passed parameter.
   *
   * @param state a String that represents the State that the Account is located in.
   */
  public void setState(String state) {
    this.state = state;
  }

  /**
   * This method returns the Account object's zip code.
   *
   * @return a String that represents the zip code the account is located in.
   */
  public Integer getZipCode() {
    return zipCode;
  }

  /**
   * This method sets the Account object's zip code variable according to the passed parameter.
   *
   * @param zipCode an Integer that represents the account's zip code.
   */
  public void setZipCode(Integer zipCode) {
    this.zipCode = zipCode;
  }

  /**
   * This method returns the Account object's solar-farm-id number.
   *
   * @return an Integer that represents the Account's associated solar-farm-id
   */
  public Integer getSolarFarmId() {
    return solarFarmId;
  }

  /**
   * This method sets the Account object's solar-farm-id variable according to the passed parameter.
   *
   * @param solarFarmId an Integer that represents the Account's associated solar-farm-id.
   */
  public void setSolarFarmId(Integer solarFarmId) {
    this.solarFarmId = solarFarmId;
  }

  /**
   * This method returns the Account object's capacity share.
   *
   * @return a double that represents the Account's capacity share.
   */
  public double getCapacityShare() {
    return capacityShare;
  }

  /**
   * This method sets the Account object's capacity share variable according to the passed parameter.
   *
   * @param capacityShare a double that represents the Account's capacity share.
   */
  public void setCapacityShare(double capacityShare) {
    this.capacityShare = capacityShare;
  }

  /**
   * This method returns the Account object's creation date.
   *
   * @return a SQL Date object that represents the Account's date of creation.
   */
  public Date getCreatedDate() {
    return createdDate;
  }

  /**
   * This method sets the Account object's created date variable according to the passed parameter.
   *
   * @param createdDate a SQL date object.
   */
  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }
}
