package com.customertracker.CustomerTracker.Models;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * This class represents a model for a Customer at Solstice, containing information relevant to a
 * Customer's account.
 */
@Entity
@Table(name = "customers")
public class Customer {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;

  private String first_name;

  private String last_name;

  private String email;

  private String active;

  private Integer account_manager_id;

  private String reason_for_joining;

  private String date;

  /**
   * Constructor constructs a Customer object will all null or -1 values representing an empty
   * Customer object.
   */
  public Customer() {
    this.first_name = null;
    this.last_name = null;
    this.email = null;
    this.active = null;
    this.account_manager_id = null;
    this.reason_for_joining = null;
    this.date = null;
  }

  /**
   * Constructor constructs a Customer object and initializes all class variables according to the
   * passed in parameters.
   *
   * @param firstName        a String representing the Customer's first name.
   * @param lastName         a String representing the Customer's last name.
   * @param email            a String representing the Customer's email address.
   * @param active           a boolean representing if the Customer's account is active, true for
   *                         active, false for inactive.
   * @param accountManagerId a Integer representing the ID of the Account Manager for the customer's
   *                         account.
   * @param reasonForJoining a String providing the reason for the customer joining Solstice.
   * @param date             a MySQL data object representing the date and time the customer created
   *                         their account.
   */
  public Customer(String firstName, String lastName, String email, String active,
                  Integer accountManagerId, String reasonForJoining, String date) {
    this.first_name = firstName;
    this.last_name = lastName;
    this.email = email;
    this.active = active;
    this.account_manager_id = accountManagerId;
    this.reason_for_joining = reasonForJoining;
    this.date = date;
  }

  /**
   * This method returns the Customer object's ID.
   *
   * @return an Integer representing the Customer's ID.
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method sets the Customer object's ID. This method does not work as the ID is auto
   * generated by the MySQL server.
   *
   * @param id an Integer representing the Customer's ID.
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method returns the Customer object's first name.
   *
   * @return a String representing the Customer's first name.
   */
  public String getFirst_name() {
    return first_name;
  }

  /**
   * This method sets the Customer object's first name according to the provided parameter.
   *
   * @param first_name a String representing the Customer's first name.
   */
  public void setFirst_name(String first_name) {
    this.first_name = first_name;
  }

  /**
   * This method returns the Customer object's last name.
   *
   * @return a String representing the Customer's last name.
   */
  public String getLast_name() {
    return last_name;
  }

  /**
   * This method sets the Customer object's last name according to the provided parameter.
   *
   * @param last_name a String representing the Customer's last name.
   */
  public void setLast_name(String last_name) {
    this.last_name = last_name;
  }

  /**
   * This method returns the Customer object's email.
   *
   * @return a String representing the Customer's email address.
   */
  public String getEmail() {
    return email;
  }

  /**
   * This method sets the Customer object's email according to the provided parameter.
   *
   * @param email a String representing the Customer's email.
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * This method returns the Customer object's active status.
   *
   * @return a String representing the Customer's status of having an active or inactive account.
   * 1 for active and 0 for inactive.
   */
  public String getActive() {
    return active;
  }

  /**
   * This method sets the Customer object's active status according to the provided parameter.
   *
   * @param active a String representing the Customer's status if they have an active account or
   *               not.
   */
  public void setActive(String active) {
    this.active = active;
  }

  /**
   * This method returns the Customer object's Account-Manager-ID.
   *
   * @return an Integer representing the ID of the Account Manager who manages the Customer's
   *         account.
   */
  public Integer getAccount_manager_id() {
    return account_manager_id;
  }

  /**
   * This method sets the Customer object's account manager ID according to the provided parameter.
   *
   * @param account_manager_id an Integer representing the Customer's account manager's ID.
   */
  public void setAccount_manager_id(Integer account_manager_id) {
    this.account_manager_id = account_manager_id;
  }

  /**
   * This method returns the Customer object's reason for joining.
   *
   * @return a String representing the Customer's reason for joining Solstice.
   */
  public String getReason_for_joining() {
    return reason_for_joining;
  }

  /**
   * This method sets the Customer object's reason for joining according to the provided parameter.
   *
   * @param reason_for_joining a String representing the Customer's reason for signing up with
   *                         Solstice.
   */
  public void setReason_for_joining(String reason_for_joining) {
    this.reason_for_joining = reason_for_joining;
  }

  /**
   * This method returns the Customer object's date they created their account.
   *
   * @return a String representing the date the Customer created their account.
   */
  public String getDate() {
    return date;
  }

  /**
   * This method sets the Customer object's date they created their account according to the
   * provided parameter.
   *
   * @param date a SQL date object representing the date the Customer created their account.
   */
  public void setDate(String date) {
    this.date = date;
  }

}
